-- https://dbdiagram.io/d/673cf0a3e9daa85aca05336c
CREATE TABLE Role (
	id SERIAL PRIMARY KEY,
	role VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE Employee (
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	email VARCHAR NOT NULL, 
	password VARCHAR NOT NULL,
	role VARCHAR NOT NULL REFERENCES Role(role) ON DELETE NO ACTION
);

CREATE TABLE TasksDescription (
	id SERIAL PRIMARY key,
	task_description VARCHAR(256) NOT NULL,
	leaderID INTEGER NOT NULL,
	FOREIGN KEY(leaderID) REFERENCES Employee(id) ON DELETE CASCADE
);

CREATE TABLE TasksAssignment (
	taskID INTEGER NOT NULL,
	employeeID INTEGER NOT NULL,
	FOREIGN KEY (taskID) REFERENCES TasksDescription(id) ON DELETE CASCADE,
	FOREIGN KEY (employeeID) REFERENCES Employee(id) ON DELETE CASCADE
);

CREATE TABLE Level (
	weight INTEGER UNIQUE NOT NULL,
	level VARCHAR(32) UNIQUE, 
	description VARCHAR(128)
);

CREATE TABLE Hardware (
    id SERIAL PRIMARY KEY,
    product TEXT UNIQUE NOT NULL
);

CREATE TABLE Software (
    id SERIAL PRIMARY KEY,
    product TEXT UNIQUE NOT NULL
);

CREATE TABLE Processes (
    id SERIAL PRIMARY KEY,
    process TEXT UNIQUE NOT NULL
);

CREATE TABLE TaskHW (
    id SERIAL PRIMARY KEY,
    task TEXT UNIQUE NOT NULL
);

CREATE TABLE TaskSW (
    id SERIAL PRIMARY KEY,
    task TEXT UNIQUE NOT NULL
);

CREATE TABLE SkillsHW (
    id SERIAL PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES Employee(id) ON DELETE CASCADE,
    product TEXT NOT NULL REFERENCES Hardware(product) ON DELETE NO ACTION,
    task TEXT NOT NULL REFERENCES TaskHW(task) ON DELETE NO ACTION,
    level TEXT NOT NULL REFERENCES Level(level) ON DELETE NO ACTION,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SkillsSW (
    id SERIAL PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES Employee(id) ON DELETE CASCADE,
    product TEXT NOT NULL REFERENCES Software(product) ON DELETE NO ACTION,
    task TEXT NOT NULL REFERENCES TaskSW(task) ON DELETE NO ACTION,
    level TEXT NOT NULL REFERENCES Level(level) ON DELETE NO ACTION,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SkillsPR (
    id SERIAL PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES Employee(id) ON DELETE CASCADE,
    process TEXT NOT NULL REFERENCES Processes(process) ON DELETE NO ACTION,
    level TEXT NOT NULL REFERENCES Level(level) ON DELETE NO ACTION,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
